Initial crawler/parsers for Full Disclosure
sailuh/perceive pull request #74
Opened 2017-10-05 04:20 UTC by jgwl

2017-10-05 04:28 UTC, jgwl commented
FYI, the guidelines say to use "#70" in the commit message, but the hash makes it look like a comment to git.

2017-10-05 04:38 UTC, carlosviansi commented
Thanks for the PR! 

If you are doing on "git commit -m" then it is not a problem, since you need to use `''`. What did you use?

Without the `#` symbol it won't link the commit (see how it is different hovering over See for example PR 71 (I don't want to add the link or it will create a tie to that issue being unrelated). The branch is more so for our `waffle` integration, so Github won't recognize if we ever have to stop using it.

We can still fix it with a git rebase using the approach in [the accepted solution of this stackoverflow question](https://stackoverflow.com/questions/35016573/escape-character-in-interactive-rebase-commit-message) (I alread to use it before to fix a few commits on @kavashashank commits so I know it works).

If you want, you can grant me write access to your fork and I can fix this. Let me know what you prefer!

I will make a formal review as soon as I can, I have an international trip coming up this weekend so everything is squeezed!

2017-10-05 05:16 UTC, jgwl commented
Ok, I combined -m with --amend, seems to have worked.

Let's catch up after you get back next week about how we want to handle the database for the index files. Also, I'll go and run the parser against all of the FD data and put it in a mega file or something similar.

2017-10-05 06:51 UTC, carlosviansi commented
@jgwl Looks great! Thank you for fixing this so quick! Your proposal sounds good to me.

## Tiny detail before I get time for a review for your future reference

One particular thing I noticed on your notebook: When you run pressing `shift+enter`, it always add one empty tab. Note your current notebook has an empty block at the bottom. This is a small detail and I can remove later myself, but I thought I would point you to it so you avoid it on the following ones :-) 

## Next-steps

So that you have a fixed goal in mind as you download the data and until I have a chance to formally review the code: 

- I would suggest you start downloading both Full Disclosure and Bugtraq on the years 2013 and 2012 (in this order) since we have been getting some interesting findings on the other end of the pipeline (I will share with you once I get the chance to put my head out of the water). 

- You can open a separate branch from this one (so we can have a separate Pull Request) and create a separate Notebook (so we don't run into merge conflicts but also since it is a separate portion) that plots the tags for these 2 years as a starting point. From what I remember you mentioning, it seems `talon` didn't yield good results. if you happen to find any other signature parser or try a few heuristics, this could become interesting. For example:

```
Regards,
```

or 

```
Sent through the Full Disclosure mailing list\nhttps://nmap.org/mailman/listinfo/fulldisclosure\nWeb Archives & RSS: http://seclists.org/fulldisclosure/
``` 

Could be good starting points to identify regions for e-mail signatures in this mailing list and seek for delimiters with one or more `-`. Creating an output table showing how many `hits` it gets applying these heuristics independently could make it easy to inspect them manually within 1-year time scope, which is usually the maximum amount of months we look at or even serve as training data for us to create a classifier for this mailing list :-)

2017-10-08 21:40 UTC, jgwl commented
For now, I've created a function to directly strip out the FD common footer. I need to spend more time looking at talon and/or alternative signature parsers.

BTW, here are the filesets for 2012 and 2013. As we refine the parsers, I can easily rerun them against the raw data.
2012 files: https://mega.nz/#!BuRhUISQ!BgPZ3MiFPMmFI7YyvbRh2Eoj22KJGZyWVLFPNzLTH0o
2013 files: https://mega.nz/#!cqgX1Y4J!GqaN5iav8GFfjzg7dTvDW-DHamT_3ktVf68xMMJLKyc

2017-10-11 20:44 UTC, carlosparadis commented
Awesome! I am almost back in Hawaii, I should have time to look at everything this weekend :-)

2017-10-22 01:55 UTC, carlosparadis commented
@jgwl :-) Alright I finally got the chance to put my head out of the water to do a reviews week. Here are a couple things I have as suggestions. Let me know if you prefer to fix them within this PR or you prefer accepting this and moving to a few separate issues to them. 

## PR Details

- The second commit is missing an issue ID `remove common FD footer`. Needs to be re-labeled. This commit appears to eliminate the ability to use talon. Rather than scrape it out, I think it would be the better idea to leave as optional to use either talon or the FD footer through heuristics. Let me know if I misunderstood. 

## Reproducibility

- PR is missing a `README.md`. Ideally, a student should only need to look at this README to know how to get more data, what the files he will get will look like (so some of the discussion of our extensions would go in it). A quick mention to what expect of each script and notebook file is about would be also helpful, and how to run them (well, aside from the notebook I guess which is standard). 
- None of the 3 scripts has a main that accept arguments, and the notebook does not use them to run. I feel we are missing the shell way to just get raw data from a start timestamp to end timestamp (and the main would need to contain some timer that doesn't end up giving the machine an IP block). I see you got the data out, but I don't see the script that you run to effectively do it, just the functions that appear part of it. Did I miss something? 
- Some additional details on the function documentation will be noted inline on the first commit will be added after this comment (I will edit here once I am done).  


## Data Formats

I see from your notebook that you created a new json ID in the `.body_tags` file. The format looks great, and it looks extensible without affecting prior code. :) This should also be noted in the README.md, as a minimal schema of what ids to expect and content.

2017-10-22 01:57 UTC, carlosparadis requested changes
See comment for the last 2 commits comments.

2017-10-23 05:51 UTC, jgwl commented
Thanks for the review! I'll add most of the changes onto this PR, since my updates aren't a dependency for others right now. But, I'll put BugTraq work into another PR.

The second commit is still using talon. Its usage was moved inside of the new strip_sig_footer function (144:145) , which performs that plus the common FD footer parsing. So, I think we can leave the filenames as is?

I saw my current notebook as an exploration of the libraries used, not really on how to accomplish the output that we're coming up with. Do you want me to add another notebook using the libraries I've created? For now, I'll add something that has a main, and note on its usage in a README.md. I'll also add more info about the JSON structure for the tag info I pulled out.

2017-10-23 08:20 UTC, carlosparadis commented
> The second commit is still using talon. Its usage was moved inside of the new strip_sig_footer function (144:145) , which performs that plus the common FD footer parsing. So, I think we can leave the filenames as is? 

Ooops I may have overlooked it. I guess I need a bit more understanding of what you refer on the notebook as the `Full Disclosure footer` so we can agree if we leave as it is or not. Did I get it right this Footer is always on every e-mail on Full Disclosure, while the signature is the varying component?

> I saw my current notebook as an exploration of the libraries used, not really on how to accomplish the output that we're coming up with. Do you want me to add another notebook using the libraries I've created? For now, I'll add something that has a main, and note on its usage in a README.md. I'll also add more info about the JSON structure for the tag info I pulled out.

I think if you could marry the library choice rationale together with how to run in a single narrative would be better than two notebooks, what do you think? :-) As far as the notebook growing too large, I suggested to another team member to split the function definitions into a separate file (in which case you already have one) and import into the Notebook. Let me know if this makes sense!

> Also, for next steps: I do have some code that parses the index file, identifies parent threads, etc. You mentioned that you just wanted to move into creating a db to hold this info, so I was planning on working on that before I moved forward on those files. I can easily generate what data I've extracted into csv, if we'll want both in the future.

Wait, really? Which file in the data you sent me has that? I was expecting something like those .csvs you saw in the Full Disclosure corpus that contains on each column the e-mail title, author, timestamp and which is the reply thread (which I was hoping to be the ancestor e-mail instead). 

Thanks for the quick response! :-)

2017-10-23 14:28 UTC, jgwl commented
> > Also,  for next steps: I do have some code that parses the index file, identifies parent threads, etc.

> Wait, really? Which file in the data you sent me has that? I was expecting something like those .csvs you saw in the Full Disclosure corpus that contains on each column the e-mail title, author, timestamp and which is the reply thread (which I was hoping to be the ancestor e-mail instead).

It's in fd_index_parse.py; read_messages() is used recursively to walk through the `<li>` structure and get the parent information from there. Right now it's just data in-memory and doesn't output anything (I was waiting until we designed the db), but I will output to CSV for now so you can have the info.

2017-10-24 20:47 UTC, carlosparadis commented
> From what I've seen, every message has that footer. If it doesn't, then nothing will get stripped out, so we're pretty safe.

Sounds good then. I guess we just need to mention all files parse out the footer and provide an example of what it tries to remove since it is not explicit in the extension name of `body`.

> I guess it depends on what you would like to have documented for future devs: how the library works, or how to use the library? I feel that if I change the notebook to just use my defined functions, then how the library works is lost. It's not anything that complicated, but useful in case you need to redo all my work :)

Let's go with what you suggested of a second notebook then, no point in losing what is already done! I will see what I do down the road!

2017-10-26 04:13 UTC, jgwl commented
I've added main(), and rearranged the structure to use "seclists" instead, since we can use this for both FullDisclosure and Bugtraq. I've also added READMEs.

I decided not to create another notebook for usage; since this procedure can download /generate hundreds of files, it didn't seem like a good idea to have it embedded there. Hopefully my README is enough documentation to get started?

Everything's squashed, so ready for your review again :) 

## Future work:
I will look into the index csv work in another PR, as well as looking into stripping out PGP pieces. I have raw files downloaded from 2007 to 2016 so far, but I was going to finish the csv index work before I push up to mega.

2017-10-26 09:03 UTC, carlosparadis commented
@jgwl Looks great, thanks for the quick pass. I will get back to you still this week. Would you mind taking a look on #77 and tell me if you have any input? This licensing part is not really my alley but we do need to license the code with something middle ground.

2017-11-05 07:53 UTC, carlosparadis commented
@jgwl Hey :-) Sorry it took me a bit again to give you a detailed review on this. 

## Crawler 

Crawler looks ready to go! It runs just fine here. I didn't test the entire year because I will be in trouble if I get an IP Block on my side, but I will see if I can test elsewhere. It was really nice how you made the functions explicit for reuse and code extension. I will use this as an example from now on! 

## Parser 

Parser there are a few minor things I am confused about!

### [README.md](https://github.com/jgwl/perceive/blob/70-full-disclosure-crawler-parser/Parsers/SecLists/README.md#parse_replyfilename)

#### 1) 

In the `parser_reply` function documentation, you use the word "Download":

> Download individual message.

Do you mean Parse individual message?

#### 2) 

In the example you give:

`$ python seclists_reply_parse.py -d ./2011_01`

Script `seclists_reply_parse.py` is used.  I see your PR however also sends an (older?) file named:

`seclists_index_parse.py` which does not have a help message and is not mentioned in the README.md. What it's purpose? 


## Misc

### Expliciting Library Dependencies 

I know we can add something called [requirements.txt](https://pip.readthedocs.io/en/1.1/requirements.html) so we can run a `pip` command to install all the necessary dependencies, besides making them explicit rather than look in the code. Maybe it would be interesting adding one for each folder (Crawler, Parser) so that other students can download everything in one go. As far as I am aware the dependencies are `requests` for Crawler, and `bs4` and `talon` for Parser. Is this correct?

### Output parameter -o 

For both Crawler and Parser, rather than default to save in the folder the script is run, an optional parameter -o could be useful for both Crawler and Parser. For us who will be versioning the code, this would avoid having to move the files manually every time we download a new month and makes it more scriptable from the command line. 

### Yearly Parser

Would it be tricky to add one additional function to parse the entire year folder and give it as an optional flag argument to the script version, just like you did for the crawler to download the entire year? 

# Notebook Review

I will edit this post soon after I finish it, but I wanted to get the feedback to the script side out. Let me know what you think!

2017-11-10 20:47 UTC, carlosparadis commented
## Some Suggestions for the .csv metadata parser

These are based on the files I have seen on the data you have shared on the 2 datasets. I thought I would note here before forgetting.

### Timestamp

#### Granularity 

The current timestamp is in the format: 2013_12_31, and we are missing the time portion and timezone.

#### Format

I would also recommend you to use a standard format for them so we can easily parse, for example:  2016-11-06 00:23:00-10:00 (the -10:00 is representing the HST timezone).

I actually found a way around going back and forth in timezones using pandas, but pendulum is equally fine. [See Section 5 for an example with Pandas.](https://github.com/erdl/sensors/blob/master/weather_underground/Weather%20Underground%20json%20to%20csv%20Data%20Parser.ipynb)

### Author 

For the author part I would also suggest to keep both name and e-mail as part of the same column, rather than parse only the name as sometimes that is the only way to distinguish them (e.g. in 2013_Jan):

```2013_01_28    ESA-2013-001: EMC NetWorker Buffer Overflow vulnerability    8-Jan    Security Alert    

2013_01_29    [security bulletin] HPSBUX02829 SSRT100883 rev.1 - HP-UX Running X Font Server (xfs) Software, Local Denial of Service (DoS), Unauthorized Access    8-Jan    security-alert    
```
The authors are Security Alert and security-alert. Given the large number of security alerts, we may accidentally end up calling 2 different ones by the same. It is ok to leave unparsed the way it is presented in the mailing list with both name and e-mail.

2017-11-25 05:57 UTC, carlosparadis commented
Here is the review of this pass for the record. Once I am done with item 3 (hopefully tonight), I am accepting this PR and putting these features/fixes in a new issue. 

## 1. Crawler

### 1.1 Still doesn't provide an optional flag as save path. 

### 1.2  README.md 

Should mention what the user is expected to be downloaded. Currently, it is each individual e-mail html page + an index.html page whose name format is <year>_<Mon>.raw.html. Main difference being the absence of a relative id in the file name. 

## 2. Index Parser 

### 2.1 Script help message example is incorrect (?)

```
-f <filename>, parse single raw file, e.g. -f ./2011_Jan_0.raw.html
```

From your `README.md` (very nicely done by the way), I assume this would be without the 0 in it? i.e. `2011_Jan.raw.html`. 

### 2.2 Lacks save path 

Currently adds to the input path directory. 

### should mention on README.md possible-follow ups case

should mention in the readme "possible-follow ups" are added to the parser the same way as follow-ups without any "possible" statement. 

- E.g. possible-follow-up I tested: `http://seclists.org/fulldisclosure/2017/Nov/index.html` has 1. 

I also tested months without any follow-ups (Bugtraq has many) and it worked just fine. Good job! 👍 

## 3. TODO(Carlos) test all e-mails were downloaded

(Will edit here later)

2017-11-25 09:45 UTC, merged